.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This branch creates a bunch of documents to describe the project at a technical level, set-up a bunch of standards and meet standardise things like raising and describing PR and Issues.
1. Create a README.md
1. Create a CODE_OF_CONDUCT.md
1. Create a CONTRIBUTING.md
1. Create .github/ISSUES_TEMPLATE/
1. Create a pull_request_template.md
***
Not everything in the project organisation section of the README.md is in the repo yet. This is fine.
=> Document: Community standards

.Rbuildignore, .Rprofile, .pre-commit-config.yaml, DESCRIPTION, README.md, inst/WORDLIST, renv.lock, renv/.gitignore, renv/activate.R, renv/settings.dcf
This branch implements DevOps best practice in adding automated checks that are run before each commit. It uses the [precommit](https://github.com/lorenzwalthert/precommit) package to achieve this.
Please see the motivating example below for this change:
> Claude is working on a project to connect to the Facebook API and show his profile and updates on a dashboard with Antoinette.
> To connect to the Facebook API, Claude needs to sign-up and use a secret token generated for his account.
> As this token is stored as a file on his computer and he is using it for this project, he stores it in the repo.
> Given that this token allows access to his account, Claude should not reveal it to anyone else.
> - This includes not storing and publishing it on the repo.
> - Ideally, he should either not …
=> DevOps: Precommit

README.md
This branch adds a small change to include our Trello board link to the README.
***
=> Document: Trello link

inst/app/global.R, inst/app/modules/main_map.R, inst/app/server.R, inst/app/ui.R, inst/app/www/styles.css, renv.lock
This branch add the basic interactive map view for the collusion location map tab.
1. Add interactive leaflet map to show collision data
1. Add the basic filter panel to filter the collision data according to the following attributes:
- Date of accident (`Date`)
- Number of casualties (`No__of_Casualties_Injured`)
- Type of collision (`Type_of_Collision`)
- Severity of accidents (`Severity`)
1. Add custom css file for filter panel
***
***
=> Feature: Interactive map and basic filter panel

inst/app/modules/main_map.R, inst/app/ui.R
This branch refines the filter panel by using alternative buttons and reorder the filters.
1. Change UI of severity type filter (`severity_filter`) to multiple checkboxes
The old filter is a drop-down list. Now replaced with a filter of multiple checkboxes.
1. Add a filter of casualty type
This filter filters the dataset by the types of casualties involved in each accident, including **Pedestrian**, **Driver** and **Passenger**. Note that selecting multiple inputs means filtering accidents including ANY of the selected classes, instead of includes ALL of the selected classes. For example, when the users choose both **Pedestrian** and **Driver** in this filter, collisions which 1. casualties include only pedestrians; 2. casualties include only drivers and …
=> Feature: Refine filters

inst/app/global.R
This branch fixes the deploy error in shiny by adding back the source of `collapsibleAwesomeCheckboxGroupInput` function.
1. source the `utils.R` files (which stores miscellaneous functions used to create the UI of the dashboard) in the global file of the shiny app.
***
```
2021-11-21T17:05:31.287567+00:00 shinyapps[5175132]: Listening on http://127.0.0.1:39389
2021-11-21T17:05:31.423681+00:00 shinyapps[5175132]: Warning: Error in collapsibleAwesomeCheckboxGroupInput: could not find function "collapsibleAwesomeCheckboxGroupInput"
2021-11-21T17:05:31.430163+00:00 shinyapps[5175132]:   108: div
2021-11-21T17:05:31.430164+00:00 shinyapps[5175132]:   107: column
2021-11-21T17:05:31.430160+00:00 shinyapps[5175132]:   109: dots_list
```
=> Fix: Source files storing utils function

inst/app/ui.R, inst/app/www/styles.css
This branch fixes the inconsistency of background color in district dashboard section.
1. Changes the background color from that of sidebar to that of main panel when user scrolls down.
After the changes:
Before the changes:
***
=> Fix: Background color of dashboard not unified

renv.lock, renv/.gitignore, renv/activate.R
This branch bump **renv** version and adds new packages used.
=> Chore: Bump renv

inst/app/ui.R
This branch removes obsolete UI chart components and refines wordings.
***
=> Dev: Clean up obsolete code

inst/app/server.R
This branch fixes the file name of the module of data manipulation.
***
=> Fix: Correct module file name

inst/app/modules/utils.R, inst/app/ui.R
This branch adds the versioning of datasets and application.
1. Add [calendar versioning](https://calver.org/) for app
1. Add version of {hkdatasets}
***
***
Location and layout of showing the versioning are subject to detail design.
=> Feat: Add app version and data version

renv.lock
This branch tracks new packages added with `renv::snapshot()`.
***
=> chore: Snapshot new packages

inst/app/desc/information.md, inst/app/ui.R
This branch adds details and paragraphs to the project info.
1. Split the paragraphs in the project info tab into a separate markdown file (`inst/app/desc/information.md`).
1. Add two chapters inside the "Project Info" tab including:
1. About this website
2. Reference
***
***
This PR mainly aims to provide a skeleton template for adding details to the project info tab. Further details (e.g. Limitations, Tech Stack) should be added to the `information.md` file in in the future.
=> Feat: Add project info details

inst/app/desc/information.md, inst/app/ui.R
This branch adds bits and bobs to slightly refine the UI and details of the website.
1. [Collision map viewer] Adjust font size & add an icon for filter panel heading
1. [Collision map viewer] Refine description text about the number of collisions filtered
1. [Collision map viewer] Select *only* **vehicle collision with pedestrian** collision type category in the default filter setting
1. [Project Info] Add a disclaimer about the database and website
***
=> Feat: misc details

inst/app/modules/main_map.R
This branch improves the performance of the app by adding `debounce()` to reactive expressions.
1. Wrap the query filter reaction expression inside the `debounce()` function. The query reactive expression will only be computed after .75 s of inactivity from users (i.e. users do not adjust the filters in the collision map panel for 0.75 seconds).
***
***
The optimal debounce time window could be figured out by considering how fast people will check/uncheck the boxes for the vehicle type/collision type, while balancing the time to generate the output.
=> Perf: Use `debounce` to slow down query filter reactive expression

README.md
This branch adds Traditional Chinese version for the project title and description in README.
***
=> doc: Add Traditional Chinese for project title and desc

.github/workflows/rcmd_build.yml
=> ci: Use latest GH action

.github/dependabot.yml
=> ci: Create dependabot

renv.lock
=> Chore: Update packages

.github/workflows/rcmd_build.yml
This branch updates the test ubuntu version to v22.04 (originally v20.04 is used).
***
=> ci: Update test ubuntu version

renv.lock, renv/activate.R
Update base R to 4.3 and routine package update
=> Chore: Update packages 

inst/app/modules/manipulate_data.R
This branch fixes miscellaneous issues in the raw data.
1. Update the `collision_type` and `junction_type` columns in `hk_collisions` data
2. Update the `injury_degree` and `vehicle_class` columns in `hk_casualties` data, and remove the leftover `...15` column
3. Update `hk_collisions_valid_sf.gpkg` by rerunning `manipulate_data.R`
***
=> Fix: Update raw collision and casualty data

inst/app/global.R, inst/app/modules/main_map.R, inst/app/ui.R
Upkeeps the default links and language used.
=> Feat: Links upkeep 

.github/workflows/rcmd_build.yml, renv.lock, renv/activate.R
=> Chore: Update packages & fix column name in `hk_vehicles`

inst/app/modules/manipulate_data.R
This branch adds "structure type" and "road hierarchy" information for 2020 and 2021 collision data.
1. Add data into `strucuture_type` and `road_hierarchy` column of collision data in 2020 and 2021 (Previously all values are left as NA)
1. Update the spatial data (`hk_collisions_valid_sf.gpkg`) by re-running the manipulate-data.R file.
Values in `道路結構` and `道路等級` are now shown.
***
=> Feat: Add column information of 2020 and 2021 collision data

renv.lock, renv/activate.R
=> Chore: Update packages (Dec 2024)

README.md, inst/app/modules/main_map.R, inst/app/ui.R
This branch adds cleaned 2022 and 2023 collision data into the database.
1. Add 2022 & 2023 data to master data files
1. Update filter UIs' default selection year to 2023
***
=> Feat: Add 2022 and 2023 data
