Hong-Kong-Districts-Info/hktrafficcollisions

.Rbuildignore
DESCRIPTION
codecov.yml
inst/WORDLIST

This branch implements best DevOps practice in setting-up code coverage. This is a measurement of how many lines of code are executed while automated tests are running. In this regard, it is a good metric for how much testing is being done and consequently, how much of your code is being checked for errors or failures.
More information is provided on [this StackOverflow post](https://stackoverflow.com/questions/195008/what-is-code-coverage-and-how-do-you-measure-it#:~:text=Code%20coverage%20is%20a%20measurement,tests%20against%20the%20instrumented%20product.).
It uses the [covr](https://github.com/r-lib/covr) package.
Typically, this is used alongside software testing.
1. `covr` package added to repo (via `DESCRIPTION`)
1. Code report has been pushed up to …

DevOps: Code Coverage

---

inst/app/global.R
inst/app/modules/main_map.R
inst/app/ui.R
renv.lock

This branch adds two map widgets for the collision location map and creates a basic popup template.
1. Add a geocoding map widget
2. Add a change basemap map widget
3. Create a popup template to show the summary of the accidents when users click on the points
***
***
- The list of basemap tile providers included is subject to change (we may have a deeper discussion on this). In this PR I included 3 common basemap tiles as the skeleton code for easier future developments.
- The details of the popup is subject to the next release of **hkdatasets**.

Feature: Basic accident popup and map widgets

---

inst/app/ui.R

This branch aims to refine the UI of the dashboard. It brings forward the proposed changes from #16.
1. Merge 3 filters in each collision type (all collisions/pedestrian-related collision/cyclist-related collision) into single filter
1. Move filters to top of the dashboard page and visually separate the filters from the dashboard (filter panel vs. data viewer panel)
1. Wrap the whole dashboard tap inside a `tabsetPanel()` in order to track users' currently selected tab
***
***
This PR is an updated version of #17.

Feature: Refine dashboard UI 

---

inst/app/global.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/server.R
inst/app/ui.R
renv.lock

This adds the basic dashboard widgets for the *"collision related to pedestrian"* tab. It brings forward the proposed changes from #19 and #20.
1. Add 4 boxes on top of the dashboard to show major statistics from the datasets user have filtered. Current major statistics include 1. total number of collisions; 2. total number of casualties; 3. number of serious casualties and 4. number of fatal casualties.
1. Add an interactive heatmap showing the number of collisions
1. Add bar charts that classify the collisions/casualties/vehicles according to different categorical variables
***
***
Branch `dev/district-dsb-all` is parallel to this branch. While `dev/district-dsb-all` handles the logic and UI of the *"all collisions"* tab, this branch edits *"collision …

Feature: Add fundamental charts and map to pedestrian tab

---

inst/app/modules/main_map.R
inst/app/www/styles.css

This branch changes the map view of the collision map by clustering the collision data in zoom-out view.
1. Cluster collision points when the zoom level is smaller than 16 (~1:8,000, district-level zoom)
https://user-images.githubusercontent.com/29334677/136853113-dd58a10f-ad36-438d-b96a-5f9766626856.mp4
1. Change the cluster marker to a uniform colour (currently light-gray), independent from the number of points within each cluster (which is leaflet's default option)
1. Increase point size from 2.5 to 7.5, making it easier for users to click on the point at high zoom level
***

Feature: Cluster collision data on map view

---

inst/app/global.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/server.R
inst/app/ui.R
renv.lock

This branch adds the basic dashboard widgets for the "collision related to cycle" tab. This branch is mostly similar to #18. The difference is that this PR focuses the "collision w/ cycle" tab, while #18 is on the "collision w/ pedestrian" tab. 
(Please refer to #18 for images, as the chart types and layout are the same)
1. Add 4 boxes on top of the dashboard to show major statistics from the datasets user have filtered. Current major statistics include 1. total number of collisions; 2. total number of casualties; 3. number of serious casualties and 4. number of fatal casualties.
1. Add an interactive heatmap showing the number of collisions
1. Add bar charts that classify the collisions/casualties/vehicles according to different categorical variables
*** …

Feature: Add charts and maps to cycle-related collision tab

---

inst/app/modules/district_dsb_cyc.R

This branch adds "cycle track" category in road hierarchy plot for cycle-related collision.
1. For cycle-related collisions, change `NA` in *Road_Hierarchy* column to `Cycle Track/Others`
2. Add `Cycle Track/Others` category to the road hierarchy plot
***
***
In the original raw data, cycle tracks are assigned with value of `-99` in the Road_Hierarchy column. They are transformed to NA when importing the data to **hkdatasets** package.

Fix: Add "cycle track" category in road hierarchy plot for cycle-related collision

---

inst/app/modules/district_dsb_all.R
inst/app/ui.R

This adds the basic widgets for the **"All Vehicle Collision"** tab in district dashboard section, similar to #18 and #23.
1. Add 4 boxes on top of the dashboard to show major statistics from the datasets user have filtered. Current major statistics include 1. total number of collisions; 2. total number of casualties; 3. number of serious casualties and 4. number of fatal casualties.
1. Add an interactive heatmap showing the number of collisions
1. Add bar charts that classify the collisions/casualties/vehicles according to different categorical variables
1. Add a year-trend graph of the total number of collisions in the selected district
***
***
Refactoring could be considered after charts and maps from all 3 tabs (all collision/pedestrian collision/cycle …

Feature: Add fundamental charts and map to "all collisions" tab

---

inst/app/global.R
inst/app/ui.R

This branch changes the choices (i.e. 18 districts) in the area filter dropdown menu from abbreviation to full name in the district dashboard.
After the changes:
Before the changes:
***

Feat: Show full name of districts in area filter

---

inst/app/modules/district_dsb_cyc.R
inst/app/ui.R

This branch refines the charts in the "collision with cycle" tab in the district dashboard.
1. Exclude vehicles that are pedal cycles in the *Vehicle Movement Stats* plot
1. Create the *cyclist action stats* plots, which is a bar chart showing movement of cyclists during the collision. (Intrinsically same as the *Vehicle Movement Stats* plot, yet ONLY include vehicles that the pedal cycles)
***

Feat: Edit charts in the "collision with cycle" tab

---

inst/app/global.R
inst/app/modules/main_map.R
inst/app/ui.R

This branch adds new information and rearranges the order of details shown in the popup of the collision location map.
1. Add the following new information in the popup:
- Street name (`Street_Name`)
- Precision location (`Precise_Location`)
- Collision type (`Type_of_Collision_with_cycle`)
- Number of casualties (`No_of_Casualties_Injured`) with detailed breakdown
- Within 70 m of junctions (`Within_70m`)
- Road structure (`Structure_Type`)
- Road hierarchy (`Road_Hierarchy`)
2. Changes the displayed district from abbreviation to the full name (`DC_full_name`) (e.g. "WC" -> "Wan Chai")
3. Rearrange the order of information shown
- Basic identifier -> Location of collision -> Type of collision -> Involved vehicles -> Involved casualties -> Road …

Feat: Refine popups

---

inst/app/global.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/ui.R
inst/app/www/styles.css

This branch refines the uses of colors in the maps.
1. Change the representative color scheme of collision severity to the following:
- Fatal: "#FF4039"
- Serious: "#FFB43F"
- Slight: "#FFE91D"
1. Change the default basemap to `"Stamen.TonerLite"`, a greyscale basemap theme to fit the overall UI
1. Refine of the cluster marker of the collision map to darker grey with white text
1. Change the color ramp of the gridded choropleth of collision in district dashboard to purple
***

Feat: Change color scheme of collision map

---

inst/app/modules/plotly_testvisual.R
inst/app/server.R
inst/app/ui.R

This branch remove old skeleton code used for testing the UI layout of the collision map tab.
Removed UI components:
***

Chore: Remove old testing code

---

inst/app/modules/main_map.R
inst/app/ui.R

This branch adds the district filter to the collision location map.
1. Add district filter on the collision location map
Leaflet will render all filtered points, even though the points may be outside the current mapview. Therefore, it takes high memory pressure to render a large number of points/markers on the map. This improve the efficiency and rendering time of the app.
2. Remove the calendar icons on the right-hand side of the date picker
The calendar icon will change the input filter to the current date by default (see `addon` argument for `shinyWidgets::airDatepickerInput`). This is not useful in our case, where collision data is a historical dataset.
***
***
The addition of the district filter is to cater for the memory limit of shinyapps.io (1 GB). …

Feat: Add district filter

---

inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/ui.R

This branch add collision type chart & fix vehicle-related stat in cyclist tab.
1. Add **Collision Type** chart (`Type_of_collision_with_cycle` column in `hk_accidents` dataset) for all-collision and cycle-collision tab
1. Add **Vehicle Class** chart (`Vehicle_Class` column in `hk_vehicles` dataset) for all-collision tab
1. **Fix**: only include vehicles in collision type `Vehicle collision with Pedal Cycle` when computing statistics of vehicles in cyclist-collision tab. Add Explicit remark to remind that bicycle are excluded in vehicle-related stats.
***

Feat: Add collision type chart & fix vehicle-related stat in cyclist tab

---

inst/app/modules/gomap.js
inst/app/modules/hotzones.R
inst/app/ui.R

This branch adds "Zoom to selected feature" buttons for the hot zone table.
1. Add a "Zoom to selected feature" button on each row in the hot zone table viewer. When the user clicks on the button, the interactive map will automatically zoom to the hot zone of that specific row.
https://user-images.githubusercontent.com/29334677/168443561-7da1d9ed-95e5-4d7c-8c62-5b69bcab8e42.mp4
***

Feat: Add "Zoom to selected feature" button for hot zone table

---

renv.lock
renv/activate.R

This branch bumps {renv} to 0.15.5, base R from 4.1.0 to 4.2.1, as well as other packages with `renv::snapshot()`
***

Chore: Bump packages

---

inst/app/modules/hotzones.R

This branch stores Mapbox access token as an environment variable for accessing Mapbox services (currently tiles).
1. Remove the committed token (https://github.com/Hong-Kong-Districts-Info/hktrafficcollisions/pull/42/commits/9d24b193a28be1586500c2dfe509458766bfa7f2).
1. Create an environment variable `MAPBOX_PUBLIC_TOKEN` to store the Mapbox access token inside the `.Renviron` file.
1. Use `Sys.getenv("MAPBOX_PUBLIC_TOKEN")` to get the link of the pedestrian collision tile from Mapbox.
***
***
The new `.Renviron` file should
1. store in the root directory of Shiny application (`./inst/app/`)
3. publish to shinyapps.io server for deployment
See (https://stackoverflow.com/questions/39084284/how-to-pass-environment-variables-to-shinyapps) for further …

Refactor: Use environment variable to store access token

---

inst/app/ui.R
inst/app/www/styles.css

This branch changes the icon used in the severity filter (closes #59).
1. Change the symbols used in the severity filter in the collision location map from icons to circle markers (same layout used for the collision map)
1. Create two HTML classes (`filter__circle-marker` and `filter__text`) for adjusting UI layout of the filter in the external CSS file (`styles.css`)
1. Remove tick icon when that severity category is selected
***

Feat: Refine icon shown in severity filter

---

inst/app/global.R
inst/app/modules/main_map.R

Until stamen basemap locations are corrected (see #54), use CartoDB Positron as the default basemap for all interactive maps.
1. Change the default basemap to `"CartoDB.Positron"` for all interactive maps, which include:
1. collision location map
1. gridded choropleth maps of collisions in each district
1. hotzone streets location
***

Fix: Use CartoDB Positron as default basemap

---

inst/app/modules/hotzones.R
inst/app/ui.R

This branch adds cartographic improvements to the hotzone interactive map in the *Pedestrian Collision Hotzones* tab.
1. Put the hotzone streets line layer under the collision location point tile.
1. Increase the line width of hotzone layer to make it look more "balanced". It "fills up" the whole street in the basemap.
1. [Minor refactor] Replace `hotspots` in variable names to `hotzones`
***

Feat: Improve cartography of hotzone interactive map

---

inst/app/www/styles.css

This branch Align circle marker to left and text to center In the severity filter. 
1. Align the circle marker in the severity filter to left
1. Align the text in the severity filter to center
This is made by adjusting the `flex-grow` properties in flexbox.
The buttons are responsive to the layout.
https://user-images.githubusercontent.com/29334677/185645938-9b35b874-7b93-40b2-b7ef-dcdc09a5f08b.mp4
***

Feat: Refine element alignments in severity filter

---

inst/app/modules/main_map.R
inst/app/ui.R

This branch updates default selected filters and map location.
1. Update the default values of the filters of the collision map, including:
1. Change the default selected time period from *May 2016 - Jun 2016* to *Jan 2016 - Dec 2016*
1. Change default selected districts from *Kowloon City* to *"Kowloon City, Yau Tsim Mong and Shum Shui Po"*
1. Change the default selected collision type from *all collision type* to *pedestrian-related collision only*
1. Update default location of collision map to Mong Kok, with a larger zoom level (16) to see the collision point by point
***

Feat: Update default selected filters and map location

---

inst/app/desc/collision_type_filter.md
inst/app/desc/date_filter.md
inst/app/desc/district_filter.md
inst/app/desc/severity_filter.md
inst/app/desc/vehicle_class_filter.md
inst/app/global.R
inst/app/server.R
inst/app/ui.R
renv.lock

This branch adds help buttons (info buttons) for describing how to use the filters in the collision location map.
1. Add {shinyhelper} dependency. 
2. Add help buttons next to the following 5 filters:
1. District filter
2. Date filter
3. Severity filter
4. Collision type filter
5. Vehicle class filter
3. Add help texts for the aforementioned buttons in the `inst/app/desc` folder.
https://user-images.githubusercontent.com/29334677/185981728-3aece3cc-06ad-47b6-8cc8-37d380222ce4.mp4
***

Feat: Add help buttons for filters

---

inst/app/ui.R

This branch adds an embedded Google Form for user survey.
1. Add a new tab in the sidebar named "User Survey"
1. Embed a Google Form in the "User Survey" tab
***
***
The height of the embedded Google Form `iframe` is currently hardcoded. In terms of best practice, the height should be computed according to users' device width.

Feat: Add embedded user survey Google Form

---

inst/app/global.R

This branch removes conflict messages in shiny app log. As the masked function behaviour is expected, it is unnecessary to keep the conflict messages. This also reduces the number of unnecessary logs in the shiny app.
***
***
The current list of objects masked when attaching the library are listed below.
```
Attaching package: ‘dplyr’
The following objects are masked from ‘package:stats’:
filter, lag
The following objects are masked from ‘package:base’:
intersect, setdiff, setequal, union
...
Attaching package: ‘shinydashboard’
The following object is masked from ‘package:graphics’:
box
...
Attaching package: ‘plotly’
The following object is masked from ‘package:ggplot2’:
last_plot
The following object is masked from ‘package:stats’:
filter
The following object is masked from …
```

Refactor: Remove conflict msgs in shiny app log

---

inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R
inst/app/www/styles.css

This branch adds live translation to collision map filter panel.
https://user-images.githubusercontent.com/29334677/188330981-cb680d02-cea4-4560-b0af-7882fa6602c7.mp4
1. Add live translations to the text in the filter panel
1. Add live translation to the filters, including:
- District filter
- Date filter (From and to)
- Collision severity filter
- Collision type filter
- Vehicle involved filter
***
***
The helper texts inside the help icon (generated from `shinyhelper::helper`) are not yet translated. Chinese translation to the markdown documents ended with *_filter* in `desc` needs to be added.

Feat: Add live translation to collision map filter panel

---

inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R
inst/app/www/styles.css

This branch changes the start/end date filter to one single date picker (address and close #72).
1. Use the `range = TRUE` option to create a date range `airDatepickerInput`. This incorporates both `start_month` and `end_month` input value into one single calendar.
2. Shorten the name of the month to abbreviated version (e.g. `January` -> `Jan`)
3. Change the color of the date picker UI from default blue to black (`#0d0d0d`)
***

Feat: Use range input to select the date range of the collision filter

---

inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv

This branch adds link to Google Street View in popup.
1. Adds a link to Google Street View in the popup of the collision, which is in the format of
```
https://maps.google.com/?cbll=latitude,longitude&cbp=0,bearing,0,zoom,tilt
```
When users click on the link, a new tab showing the street view will be opened.
https://user-images.githubusercontent.com/29334677/189707872-ad7afff9-7d12-4a9d-bf81-7addfe90de44.mp4
***
***
Known issues of going to street view by only providing longitude and latitude:
1. Cannot distinguish whether location is in ground level/flyover/underground
2. When there is no street view available for the location of the collision point, the link will look for the nearest community-contributed panorama

Feat: Add link to Google Street View in popup

---

inst/app/desc/hotzone.md
inst/app/desc/information.md
inst/app/desc/key_facts.md
inst/app/global.R
inst/app/modules/hotzones.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch completes the traditional Chinese translation of the website (except *District Dashboard* tab).
1. Set traditional Chinese (*zh*) as the default language of the website
1. Complete traditional Chinese translation to *Key Facts* and *Project Info* tabs
1. Remove the *Data Download* tab until the method of hosting data is resolved
1. Add a description in the collision map filter tab that collision points shown are updated automatically after filters are changed
***
***
Both *zh* and *en* versions of the paragraphs in *Key Facts* and *Project Info* are shown regardless of the users' currently selected language. This is because paragraphs of both languages are stored in the same markdown file, then rendered to the website using `includeMarkdown()`. …

Feat: Complete traditional Chinese translation of website

---

inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch adds a "Zoom to filtered collision" button in the collision location map (partly addresses and closes #79)
1. Adds a "Zoom to matched collisions" button in the filter panel. When the user clicks on the button the extent of the map will be reset to the boundary (bounding box) of the currently filtered collision points.
https://user-images.githubusercontent.com/29334677/189742813-95e64697-e026-4de8-91b2-a3f8f2dce721.mp4
***
***
`st_bbox()` maybe overkill to find out the boundaries of the currently filtered collisions. Need to benchmark the performance of the website.

Feat: Add "Zoom to filtered collision" button

---

inst/app/ui.R

This branch sets a maximum width for paragraphs inside `box` for an easier reading experience.
1. Set maximum width (currently 640px) for boxes that include mostly paragraphs. The two major tabs affected are "Project Info" and "Key Facts".
***

UI: Set max width for paragraphs

---

inst/app/modules/main_map.R
renv.lock
renv/.gitignore
renv/activate.R

Chore: Bump {renv} to `0.16` and update packages

---

inst/app/modules/main_map.R

This branch suppresses `i18n` warning message when translating road hierarchy with `NA` values.
1. Suppress the following error when `i18n$t` is used to translate road hierarchy values for the map popup.
```
Warning in private$raw_translate(keyword, translation_language) :
'NA' translation does not exist.
```
***
***
The following code cannot suppress warning message. Maybe caused by the vectorisation execution behaviour of `ifelse`?
```r
tags$b(i18n$t("Road hierarchy: ")),
ifelse(is.na(filter_collision_data()$Road_Hierarchy), "N/A", i18n$t(filter_collision_data()$Road_Hierarchy))
```

Fix: Suppress `i18n` warning message when translating road hierarchy

---

inst/app/modules/main_map.R

This branch shows collisions in all district by default & restrict max no. of points shown on the map.
1. Show collisions in all districts by default. Originally, only Kowloon City (KC), Yau Tsim Mong (YTM) and Shum Shui Po (SSP) are selected in the district filter. 
1. Restrict the maximum number of points returned from the filters to **20,000**.
1. Show a warning/error message when the number of records filtered exceeds 20,000.
***
***
A better warning/error message should be designed, like [changing colour](https://stackoverflow.com/questions/60618714/change-color-of-notification-in-r-shiny) and [line breaks](https://stackoverflow.com/questions/46290869/how-to-break-line-in-long-shownotification-for-rshiny) between Chi and Eng message.

Feat: Show collisions in all district by default & restrict max no. of points shown on map

---

inst/app/modules/district_dsb_all.R

This branch simplifies the year trend graph of the total number of collisions in the dashboard. 
1. Simplify the collision number year trend graph by:
1. Showing only years within the selected year range
2. Remove the background annotation showing the selected year range
1. Directly use the filtered dataset from the reactive expression `ddsb_filtered_hk_accidents()`. Previously, the chart filters the dataset again in order to show the numbers of all covered years. For example, when the users choose the year range from 2015-2018, the year trend line still covers all years from 2014 to 2019.
***

Feat: Simplify collision by-year trend graph

---

inst/app/modules/district_dsb.R
inst/app/modules/district_dsb_all.R
inst/app/server.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch adds traditional Chinese live translation to the control options of dashboards.
1. Add an overarching module file (`district_dsb.R`) to store the fundamental reactive expressions and UI for the dashboard
2. Add traditional Chinese live translation to the options available for control collisions shown on dashboard, including:
1. District
2. Year range
3. Collision Severity
***

i18n: Add translation of control options of dashboards

---

inst/app/modules/district_dsb.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch revises the UI for users to choose different options of the dashboard.
1. Unify the height of the three option widgets (District, Year range and Killed/Seriously Injured (KSI)) by merging them into a single `box` with same column width.
2. Add tab title (Dashboard).
3. Reverse space for adding the description of the page and usage of the options.
***

Feat: Revise dashboard options UI

---

inst/app/modules/district_dsb.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch translates charts in the dashboard tab.
1. Add Chinese translations for the plots.
2. Remove plot titles. The title of the charts is shown as box titles instead for consistency of layout.
3. [REFACTOR] Remove colons from texts to be translated. Colons are written outside the `i18n$t()` functions. (e.g. `i18n$t("Road hierarchy: "))` -> `i18n$t("Road hierarchy"), ": ")`)
***
***
1. The method of directly writing the translation terms as dataframes has to be revised.
2. The translation of the charts could have two options, including a. using bilingual axis category text (Used in this PR) or b. Live translation to show only the axis category text of the currently selected language. The plot would be constructed like
```r
plot_by_severity = ggplot( …
```

i18n: Translate charts in the dashboard tab

---

inst/app/modules/main_map.R

This branch keeps the collision map showing individual collision points at zoom level 15 (district level, ~1:20,000).
1. Decreases the zoom level for the point clusters from 16 to 15.
***

Feat: Show individual collisions at zoom lv 15

---

inst/app/global.R
renv.lock
renv/activate.R

This branch changes all basemap back to Stamen Tonerlite style after the basemap data is updated with [Stamen Toner map tile migrated to Stadia](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/).
Closes #54 and closes #107 
1. Upgrade {leaflet.providers} to v2.
2. Use the new provider name for Tonerlite basemap.
3. Use Tonerlite as the default basemap. 
***
***
The history of change of the basemap provider service link is available at https://stamen.com/here-comes-the-future-of-stamen-maps/.

Feat: Use Stamen TonerLite as the default basemap

---

inst/app/global.R
inst/app/modules/district_dsb.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch adds 2020 and 2021 collision data into the dataset, with major changes in the column names.
1. Add cleaned and manipulated 2020 and 2021 collision data to the 4 datasets used in the app (`hk_collisions`, `hk_vehicles`, `hk_casualties` and `hk_collisions_valid_sf`)
2. Renamed `accidents` related variables to `collision`. It is to follow the “collision not accident” campaign in naming collisions/crashes, although TD still refers to the relevant tables as ‘accidents’ data.
3. Revise column names of raw collision data. Following the [tidyverse variable naming convention](https://style.tidyverse.org/syntax.html), all variables are in lowercase and separated by underscore.
4. Update default collisions shown in the map to those in 2021. Originally …

Feat: Add 2020 and 2021 collision data

---

inst/app/global.R

This branch sets the timezone of the R locale in the Shinyapps server to Hong Kong time (GMT+8) (fixes #88).
***

fix: Set shiny deployment server time locale to Hong Kong time

---

inst/app/modules/district_dsb_ped.R

This branch corrects variables (column names and values) of 2020 and 2021 new data.
1. Change the "SSPO" value in the district column of 2020 and 2021 data to "SSP". This keeps the district abbr in line with the original one.
1. Treat observations with easting and northing values of 800000 as NA values instead of valid spatial location. In raw data, 800000 refers to missing values. 
2. Change the "collision_type" column variable in the pedestrian district dashboard to "collision_type_with_cycle". This replacement is missed in #113.
***
***
Sequel for the leftover steps that should be completed in #113

Fix: correct variables of 2020 and 2021 new data.

---

inst/app/www/styles.css

This branch refines the UI of the collision map tab by restricting the height of the collision map and filter panel.
1. Set the maximum height of the collision map and filter panel. This prevents these elements from having a bigger height than the user's viewport's height.
2. Add a margin between the collision map and filter panel in a narrow screen width. 
***
***
Shinydashboard will collapse the sidebar and make fluidRow stacks when the screen width is smaller than 768px. Here narrow viewport refers to screen width smaller than 768px.
There seems to be a better way to set the height of the box containing the collision map and filter panel directly. Could consider refactoring afterwards.

Feat: Restricting the height of the collision map and filter panel

---

inst/app/ui.R

This branch reorders the tabs in the district dashboard by putting the pedestrian collision tab as the default tab.
***

Feat: Put pedestrian collision tab as the default tab in dashboard

---

inst/app/modules/district_dsb.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/translation/translation_zh.csv

This branch adds the "All Districts" category in the District Dashboard to show summary of Hong Kong overall (i.e. all 18 Districts in HK).
1. Add "All Districts" category (全港) in the district filter of the District Dashboard to allow users to view related summary figures of the whole territory.
2. Do not generate collision location map when "All Districts" is selected and show guidance message. Generating the grid map is currently computationally intensive.
***

Feat: Add "All Districts" category in District Dashboard

---

inst/app/modules/district_dsb.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv

1. Use `req()` to ensure several filter values are initialised / non-missing before running reactives to filter the data
2. Use `validate()` to indicate which filter values are not correctly selected in the District Dashboard 
3. Add thousand separator for total casualties numbers
***
***
- https://shiny.posit.co/r/articles/improve/req/
- https://shiny.posit.co/r/articles/improve/validation/

Refactor: Better handing of missing outputs

---

inst/app/global.R
inst/app/modules/district_dsb_all.R
inst/app/modules/district_dsb_cyc.R
inst/app/modules/district_dsb_ped.R
inst/app/modules/hotzones.R
renv.lock
renv/activate.R

1. Update used packages with `renv::snapshot()`
1. Fix breaking changes caused by upgrading {tmap} package from v3 to v4
***
***
The Mapbox tile for collision location in the hotzone tmap is yet to be fixed. It is suspected that currently it is not possible to directly add Mapbox map tiles using `tm_tiles()`

Chore: Fix breaking changes in {tmap} v4

---

inst/app/modules/district_dsb.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch adjusts the design on the collision map's filter panel and improves the warning message shown when the number of collisions filtered exceeds the server limit.
1. Reduce the max number of collisions shown on the map to 10,000
1. Redesign the warning message when the user selects more than 10,000 collisions as a modal pop-up window instead of a notification on the bottom right
1. Redesign the text showing the current total number of collisions filtered
1. Revise various information texts for clarity
***

Feat: Refine layout of collision map

---

inst/app/modules/district_dsb.R
inst/app/modules/main_map.R
inst/app/translation/translation_zh.csv
inst/app/ui.R

This branch reduces the maximum number of collisions shown on the map to 5,000 to cope with the RAM limit of the shinyapps.io free tier.
1. Reduce the maximum number of collisions allowed to be shown on the map to 5,000 
1. Changes the default selected districts in district filter from all 18 districts to 9 core urban districts
***

Fix: Reduce maximum number of collisions allowed to be shown
